from typing import TypedDict, Any, Dict, Optional
from app.agents.schemas import RevenueInsights, OperationsInsights, MarketInsights, MarketingInsights, ExecutiveActionPlan, ProductAnalysisResult

class SystemState(TypedDict):
    """
    The shared state dictionary that is passed between LangGraph nodes during execution.
    This acts as the memory for the single run.
    """
    # Initiated by Orchestrator
    seller_id: str
    time_window_start: str
    time_window_end: str
    snapshot_data: Dict[str, Any]  # Raw metrics (revenue drops, SLA metrics, etc.)
    
    # Per-product specific
    product_id: Optional[str]
    
    # Generated by Domain Agents (Running in Parallel)
    revenue_insights: Optional[RevenueInsights]
    ops_insights: Optional[OperationsInsights]
    market_insights: Optional[MarketInsights]
    marketing_insights: Optional[MarketingInsights]
    
    # Generated by Synthesizer (Final Step)
    final_executive_plan: Optional[ExecutiveActionPlan]
    product_analysis: Optional[ProductAnalysisResult]
